### ISSUE TITLE
cannot import name 'CompositionView' from 'sanic.views' in 21.12.x versions

### ISSUE THREAD

**Issue by NikPaushkin** [sanic-org/sanic#2360]
**Describe the bug**
Sanic fails to start with the exception above. Works fine on 21.9.3 version, seems like a regression bug described here https://github.com/RasaHQ/rasa/issues/10603

**Expected behavior**
Smooth start as with 21.9.3 version.

**Environment (please complete the following information):**
 - Windows 10, 11
 - Python 3.9

**Comment by NikPaushkin** [comment]
Nevermind, I missed that it has been deprecated https://sanicframework.org/en/guide/release-notes/v21.12.html#what-to-know

**Comment by ahopkins** [comment]
You should also ref:

- https://github.com/RasaHQ/rasa/issues/10585
- https://github.com/RasaHQ/rasa/pull/10590
